name: Deploy package

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'rc/**'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy package
        uses: crashteamdev/action-maven-deploy@v0.0.6
        with:
          jdk-version: '21'
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          deploy-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          deploy-secret-key-password: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
